server:
  port: 8081

spring:
  redis:
    database: 0
    timeout: 5000
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    #password: root
    # 连接池最大连接数（使用负值表示没有限制）
    pool:

    max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: 3000
    # 连接池中的最大空闲连接
    max-idle: 20
    # 连接池中的最小空闲连接
    min-idle: 2


#management:
#          port: 52092
#          security:
#            enabled: false
#
#info:
#        app:
#              name: "@project.name@" #从pom.xml中获取
#              description: "@project.description@"
#              version: "@project.version@"
#              parent-version: "@project.parent.version@"
#
#spring:
#    profiles:
#       active: '@env@'
#    aop:
#      proxy-target-class: true
#
#    application:
#       name: service-crawler
#
#springfox:
#  documentation:
#    swagger:
#      v2:
#        path: /api-docs
#
#endpoints:
#  shutdown:
#    enabled: true
#    sensitive: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://*****:*****/eureka
#spring:
#  application:
#    name: springboot